### ISSUE TITLE
usage with cli tools

### ISSUE THREAD

**Issue by btrepp** [lastlogin-io/obligator#27]
Hi there, this has been excellent where I have gotten it working, but wondering if it can be used in cli contexts too?.

Eg kubelogin is a kubectl plugin. I tried to configure it, but it seems to start a localhost:8000 server to manipulate (probably store) the tokens on the way through. This means the redirect URLs don't match, so obligator correctly rejects.

I am trying to figure out if these flows are actually compatible. Eg a cli tool might need some interactive page, that waits for the redirect to then persist on disk. Is this a use case obligator can support?. 

I don't mind writing some code, say a kubectl plugin, but I suspect this may be impossible to even achieve due to how anonymous Auth in obligator works.

**Comment by btrepp** [comment]
It actually works. Really well!
If you install the https://github.com/int128/kubelogin

You should get the below command, which pretty much holds your hand the entire way through and it ends up working!

```
 kubectl oidc-login setup --oidc-issuer-url=https://lastlogin.io --oidc-client-id=http://localhost
```

You really only need to swap the oidc-issuer-url (I used last login.io as a quick test). oidc client id will need to be the localhost due to how the cli login works.

But that's awesome as you can login to your k8s clusters using oidc, and not need to maintain a crap-tonne of passwords or magic files :)

Amazing service and tool :)

**Comment by anderspitman** [comment]
Sorry for the late response, but glad you got it to work!
