### ISSUE TITLE
Upgrade 0.2.0 to 0.3.0 fails with "Failed parse JSON" error

### ISSUE THREAD

**Issue by poVoq** [lastlogin-io/obligator#36]
I tried updating with the binary release, and after adapting the various run flags that changed I still get this error:
`Failed parse JSON`

When pointing `-config` to my previous .json storage file.

Any idea what might be causing this?

**Comment by anderspitman** [comment]
Hey @poVoq, sorry about that. I'm assuming you can't share your config with me, so I can try and dig up an old one and feed it into 0.3.0 to see if I can replicate the problem. I made the changes incrementally, so I never actually gave it a complete 0.2.0 config directly.

**Comment by poVoq** [comment]
My config isn't actually that important, I can discard it and make a new one, but I am a bit unsure how to do that as there is no template or anything like that for the new config file.

**Comment by anderspitman** [comment]
Right, makes sense. First thing to try (after making a backup of the config) would be to delete everything from it except for `smtp` and `oauth2_providers`, since those are currently the only thing supported.

**Comment by anderspitman** [comment]
For setting other values, you'll currently need to edit the db.sqlite directly. It would be pretty easy to add support for more things to the config though, so let me know if that would be helpful. Ideally there should be parity between the config, CLI arguments, and database.

**Comment by anderspitman** [comment]
Hey @poVoq, the problem appears to be the `users` property in the config, since it's a different format than the server is expecting. If you delete that it should load. I'll work on a more proper fix as well.

**Comment by poVoq** [comment]
Yes that seems to have fixed it. Thanks!

**Comment by anderspitman** [comment]
Excellent. I've opened a new issue to track the overall problem: https://github.com/lastlogin-io/obligator/issues/37
